# Copyright (c) 2015 Intracom S.A. Telecom Solutions. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html

sudo: required
dist: trusty

language: bash

install:
    - sudo bash deploy/provision.sh

script:
    - source /opt/venv_oftraf/bin/activate
    - sudo bash deploy/run.sh
